### ISSUE TITLE
CSV parsing challenge

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude-parse#17]
For relude-csv, @mlms13 ran into an interesting scenario when trying to parse csv fields, which are delimited by `,`, `\r\n` or `\n`.

You'd normally use `sepBy` for parsing the csv fields out, but for parsing the actual fields, you need a parser that will consume all the input up to `,`, `\r\n`, or `\n`.

Using `manyUntil` doesn't quite work b/c `manyUntil` consumes the delimiter, so it messes up the `sepBy`.

Maybe we need something like `manyUntilBacktrack` which consumes all the input and the terminator, but then backtracks to the start of the terminator?

Or another idea is a `not` function that lets you negate a parse, so you could so `many(not(anyOfStr([",", "\r\n", "\n"])))`.  I'll have to see how negation could work like this.

**Comment by mlms13** [comment]
Indeed, without getting too far into the weeds, this is [the "real life" use in question](https://github.com/reazen/relude-csv/blob/a328368b7a116abb7bc815381bad65f6c66deaa0/src/ReludeCsv_Parse.re#L26-L28).

In addition to the `manyUntil` approach, the other attempt was to use `anyCharNotIn`, which doesn't work because the terminator can be a multi-char sequence (CRLF). Both backtracking to restore the separator or `not << anyOfStr` seem like they would be good options.

**Comment by andywhite37** [comment]
Things to try

- [ ] add `not` function which runs a parser and if it succeeds, fail the parse (maybe use `lookAhead` for this?)
- [ ] look into `manyUntil` with a bracktrack - see also #18

**Comment by andywhite37** [comment]
I added a bunch of stuff in `v0.6.0` which I think should help with the csv challenges.  I made a tiny test for parsing a csv, and I think it's working more naturally.

https://github.com/reazen/relude-parse/blob/master/__tests__/ReludeParse_Tutorial_test.re#L351-L362

I'll close this, and we can re-open or open a new ticket if there are more hurdles.
